### ISSUE TITLE
system-canonicalpath-0.3.0.0 fails its test suite

### ISSUE THREAD

**Issue by peti** [d12frosted/CanonicalPath#3]
We're getting plenty of errors in our CI environment. See http://hydra.cryp.to/build/536258/log/raw for a complete build log.

**Comment by d12frosted** [comment]
Thank you for build log. I will check it soon. Meanwhile, could you provide information about your environment? Like OS, ghc and cabal versions?

**Comment by peti** [comment]
The build log contains the output from `./Setup configure -v`, which shows all that IMHO.

**Comment by d12frosted** [comment]
Oh yes, sorry. Haven't noticed that after first quick look.

**Comment by d12frosted** [comment]
Yeah, test module is a bit dummy. It depends on files that are even not included in distribution file. Starting from dd2a6d04376c736253399a5b673102d94b61c4c5 test suite creates needed files by itself. To clean them, you need to use `cabal clean`. I hope that this is the right or common way to solve such problems.

Any way I am concerned by this error:

```
equal: Left "/homeless-shelter: canonicalizePath: does not exist (No such file or directory)" is not equal to Right CanonicalPath "/homeless-shelter"
```

Actually it tests that library can build home directory from "~/" or "$HOME". But it looks like `/homeless-shelter` doesn't exist. I wanted to test it on actual environment you are using, but still haven't configured it.

**Comment by peti** [comment]
Nix builds are not supposed to access the user's home directory; we delibaratelly point `$HOME` to a non-existent location to make sure that builds don't mess with those files. IMHO, it would be much nicer to perform those tests in `$TMPDIR` (or `$TEMPDIR`). If you absolutely *need* a home directory, then we can change the our build instructions to provide one, but that won't be the real home directory either -- we'll probably just define `HOME=$TEMPDIR`.

**Comment by peti** [comment]
Oh, cleaning files with `cabal clean` is no problem: Nix builds run in a temporary locations that's wiped once the build is finished, so from our point of view you can create as many files as you please without worrying about removing them later. I think most distributions have sandboxed builds these days.

**Comment by d12frosted** [comment]
Hm, I see. Thank you for explanations. It makes the problem pretty clear. Basically, I don't access the `$HOME` directory. Test suite just requires it's existence. So what I am going to do is to change test cases that are using `$HOME` variable, so they will not require `$HOME` directory existence.

**Comment by d12frosted** [comment]
Ok, it should be fixed by now. Is it possible to test it on your setup without releasing new version? So I can release new version when I am 100% sure that it works.

**Comment by peti** [comment]
The current git HEAD fails like so:

    Test suite logged to:    Running 1 test suites...
    Test suite canonicalpath_tests: RUNNING...
    [ FAIL  ] canonical path constructors.check for extracting environment variables
      tests/CanonicalPathTests.hs:67
      equal: Left "/homeless-shelter: canonicalizePath: does not exist (No such file or directory)" is not equal to Left "/homeless-shelter/: canonicalizePath: does not exist (No such file or directory)"

    FAIL: 3 tests run, 2 tests passed, 1 test failed
    Test suite canonicalpath_tests: FAIL

**Comment by d12frosted** [comment]
Ok, second try. Looks like I just forgot trailing `/`.

**Comment by peti** [comment]
The new version works fine. Thank you!

**Comment by d12frosted** [comment]
Oh cool. Thank you very much for your effort. I will upload new version of this package soon.

**Comment by d12frosted** [comment]
Closed by 84eaac78599a9fead61a089057084e3b64206315.

**Comment by peti** [comment]
Any chance of getting a new release on Hackage?

**Comment by d12frosted** [comment]
[v0.3.1.0](https://hackage.haskell.org/package/system-canonicalpath-0.3.1.0) is available. I am sorry that it took so long to publish new version.

**Comment by peti** [comment]
No worries, thank you very much for your help!

**Comment by d12frosted** [comment]
You're always welcome. But in this case it's me who should thank. So thanks you very much for your help with fixing broken tests.
