### ISSUE TITLE
TMPDIR environment variable not found (test suite)

### ISSUE THREAD

**Issue by snoyberg** [d12frosted/CanonicalPath#4]
I just got the following test failure from Stackage:

```
Test suite canonicalpath_tests: RUNNING...
[ FAIL  ] canonical path constructors.test for extracting environment variables
  tests/CanonicalPathTests.hs:68
  right: received (Left "TMPDIR: getEnv: does not exist (no environment variable)")

FAIL: 3 tests run, 2 tests passed, 1 test failed
Test suite canonicalpath_tests: FAIL
Test suite logged to: /home/michael/Desktop/logs/stackage-nightly-2015-03-03/system-canonicalpath-0.3.1.0/test-run.out
```

**Comment by d12frosted** [comment]
Hm. The burden of testing for variables. 
Looks like `Stackage` doesn't provide `$TMPDIR`. Does it provide `$TEMPDIR`? Test suite doesn't do anything there. Just expecting that `$TMPDIR` exists.

**Comment by snoyberg** [comment]
It's running on a stock Ubuntu system, and neither of those environment
variables is defined.

**Comment by d12frosted** [comment]
Ok. Thanks for all the info. I will fix and update it in ~5-6 hours.

**Comment by d12frosted** [comment]
Should be fixed by b8c67dd9c6280c9016dedcd265cde3103c691fba. The question is: should I upload new version to `hackage`?

**Comment by snoyberg** [comment]
I just tested, and this version seems to work. So I'd be in favor of an upload to Hackage.

**Comment by d12frosted** [comment]
Done. New version is available on [Hackage](https://hackage.haskell.org/package/system-canonicalpath).
